### ISSUE TITLE
NPM package versions

### ISSUE THREAD

**Issue by bytestream** [ajmalafif/typeface-inter#5]
@ajmalafif Please could you explain the versions at NPM?

https://www.npmjs.com/package/typeface-inter appears to be in use by both https://github.com/KyleAMathews/typefaces & this repository. This repository is using v3, the other is using v1. https://github.com/KyleAMathews/typefaces is also deprecated and recommends using https://github.com/fontsource/fontsource

**Comment by ajmalafif** [comment]
hi @bytestream,

Thanks for the question and bring this to my attention as I wasn‘t aware. 

I‘ll share you context first before answering your question. Having Inter on Google Font has been a long wait dated back to 2018 (so that we can use them with (Kyle‘s typefaces package) here: https://github.com/google/fonts/issues/1455#issuecomment-422711035

However I needed them for my projects so I decided to manually host them. We had a convo on Twitter which when the time comes (Inter finally one Google Font), so he can just override the NPM package: https://twitter.com/GatsbyJS/status/1093411095551692800

Also thanks for the fontsource recommendation.

**Comment by bytestream** [comment]
Thanks for the reply, context and your work on this package @ajmalafif 

Personally I don't think Kyle should be publishing v1's on this package name. I'll justify why:
* The version convension is confusing - hence this issue
* Kyle's typefaces project is deprecated and recommends using fontsource - see https://github.com/KyleAMathews/typefaces/blob/master/packages/inter/README.md
* NPM versions 1.x have a completely different project structure based on exports from Google Fonts. Google Fonts does not export the full set of fonts (italics, etc), while this package does. Ref: https://github.com/fontsource/fontsource/issues/90

Given the last point, for me, this package still has a use case.

Perhaps @KyleAMathews can weight in. It would be preferable if those versions were removed and published under a different package name. NPM should be able to show you were anyone is actually pulling those v1's. Or at the very least, the README updated to note that there are two independent GitHub repositories publishing under separate version numbers simultaneously.

**Comment by ajmalafif** [comment]
Hi @bytestream, 

It took me awhile but I understood what‘s the issue is now and I am tempted to actually overwrite the NPM package to reflect this package. However I am probably will mess things up as I am more of a designer than a programmer so I am worried of breaking stuffs unintentionally. 

Do you mind doing a PR (like should I have a release tag for this package?) and more than happy to push the changes on NPM.

**Comment by bytestream** [comment]
I'm not familiar with NPM. I don't think there's anything I can do from GitHub.

To remove the versions I think you need to do one of the below:
* npm unpublish <package_name>@<version>
* npm deprecate <package>@<version> "<message>"

See https://www.npmjs.com/policies/unpublish

To update the README / linked repository, it looks like you need to publish a new version:

https://docs.npmjs.com/about-package-readme-files

**Comment by ajmalafif** [comment]
Thanks for these insights!

As you probably could tell I am not really familiar myself other than trying to figure out for my own use case. Give me a couple of days to make sure I don‘t break things and will update the package accordingly.

**Comment by bytestream** [comment]
No worries, take your time :) I just wanted to make you aware and find out why both versions exist

**Comment by ajmalafif** [comment]
Hi @bytestream,

I‘ve finally found the courage and reverted the npm package back to as per Inter‘s version `3.15` and since I can‘t republish the same version, I‘ve updated it to version `3.15.1` instead: https://www.npmjs.com/package/typeface-inter

Feel free to correct if I‘ve done any mistake with the package, more than happy to fix it. 

Oh and Merry Christmas & happy holidays!

**Comment by bytestream** [comment]
Thanks very much! I'll let you know if I notice anything. 

Merry Christmas to you too! 🎅
